powerpc/64-bit: Fix compilation error when PREEMPT enabled
This patch fixes compilation error
	undefined reference to `PACASOFTIRQEN'
	undefined reference to `PACAHARDIRQEN'
by putting their call under LAZE_EE flag

This error was introduced by the below patch from Paul
which has rearranged these macros definition under LAZY_EE flag

 commit d04c56f73c30a5e593202ecfcf25ed43d42363a2
    Author: Paul Mackerras
    Date:   Wed Oct 4 16:47:49 2006 +1000

        [POWERPC] Lazy interrupt disabling for 64-bit machines

    The code in 'powerpc/include/asm/hw_irq.h' was rearranged and
    cleaned-up a bit in order to reduce the number of needed #ifdef's.

Signed-off-by: Priyanka Jain <Priyanka.Jain@freescale.com>
Signed-off-by: Andy Fleming <afleming@freescale.com>